### ISSUE TITLE
Telegram notifications not working

### ISSUE THREAD

**Issue by yg** [plibither8/gh-followers-tracker#2]
/cc @plibither8

**Comment by yg** [comment]
I think there is a problem in notify() function

```js
await fetch(`https://tg.mihir.ch/${TG_BOT_NAME}`, {
		method: 'POST',
		body: JSON.stringify({
			text: message,
			secret: TG_BOT_SECRET
		}),
		headers: {
			'Content-Type': 'application/json'
		}
	});
```

**Comment by plibither8** [comment]
I have mentioned in the README that this notify function is tailor-made for my use-case only, since tg.mihir.ch provides a nifty wrapper around _my_ Telegram bots only.

To get notification on your Telegram account, this approach would not work. You would want to create your own Telegram bot, which notifies/messages you. You can have a look here: https://github.com/plibither8/tg-bots/blob/master/index.js#L27 to see how the the Telegram API is working. For more, and better, docs visit there docs site: https://core.telegram.org/bots/api

**Comment by yg** [comment]
@plibither8 I think CHAT_ID is pointing to yours here

https://github.com/plibither8/tg-bots/blob/master/index.js#L4

**Comment by plibither8** [comment]
Yes, tg-bots is for my personal use only. I have opensourced it just as a reference for others to build upon.

**Comment by plibither8** [comment]
If you need help in setting up the bot, feel free to message me :)

**Comment by yg** [comment]
Thanks @plibither8, Now I'm setting up the bot!

**Comment by yg** [comment]
Fixed in this commit https://github.com/yg/gh-followers-tracker/commit/993404c9fa4f9f97e838db265e0f3f14b5d200a6
